name: "Setup osxcross"
author: mbround18
description: Setup osxcross for rust/other compilation projects.
branding:
  icon: 'aperture'
  color: 'green'

inputs:
  osx-version:
    description: "Version of osx to use."
    required: true

runs:
  using: "composite"
  steps:
    - shell: bash
      name: Check system
      run: |
        if [[ "$OSTYPE" == "linux-gnu"* ]]; then
          echo "Found linux based system, proceeding."
          if [ -z "${{ inputs.osx-version }}" ]; then
            echo "Error!: Osx Version required!"
            exit 1
          fi
        else
          echo "Error!: Your system must be a linux based system! Try running this on ubuntu-latest."
          exit 1
        fi

    - shell: bash
      run: mkdir -p $GITHUB_ACTION_PATH/osxcross

    - shell: bash
      id: target
      run: |
        echo "::group::Disclaimer Click Here for Info"
        echo ""
        echo "-------------------------------------------------------------------------------------------------------"
        echo ""
        echo "The first time you run this it will take upwards of 9 minutes to compile. Subsequent builds are cached."
        echo ""
        echo "-------------------------------------------------------------------------------------------------------"
        echo ""
        echo "::endgroup::"

        echo "::group::Installing Deps"

        if hash sudo 2>/dev/null; then
          sudo apt-get update
          sudo apt-get install -y -qq clang gcc g++ zlib1g-dev libmpc-dev libmpfr-dev libgmp-dev cmake libxml2-dev libssl-dev xz-utils
        else
          apt-get update
          apt-get install -y -qq clang gcc g++ zlib1g-dev libmpc-dev libmpfr-dev libgmp-dev cmake libxml2-dev libssl-dev xz-utils
        fi
        echo "::endgroup::"

        OSXCROSS_FOLDER="$(echo "$GITHUB_ACTION_PATH/osxcross" | sed 's/\.\/*//g')"

        echo "::group::Cloning osxcross"
        git clone https://github.com/tpoechtrager/osxcross "$OSXCROSS_FOLDER"
        echo "::endgroup::"

        # Check setup for osx version
        echo "::group::Fetching macosx SDK"
        FILE_NAME="MacOSX${{ inputs.osx-version }}.sdk.tar.xz"

        # Check joseluisq/macosx-sdks for release
        wget -nc "https://github.com/joseluisq/macosx-sdks/releases/download/${{ inputs.osx-version }}/${FILE_NAME}" -O "$OSXCROSS_FOLDER/tarballs/${FILE_NAME}"
        echo "::endgroup::"

        echo "OSXCROSS_TARGET=${OSXCROSS_FOLDER}/target" >> $GITHUB_ENV

    - uses: actions/cache@v3
      id: cache
      with:
        key: ${{ runner.os }}-osxcross-${{ inputs.osx-version }}
        path: |
          ~/.cargo/registry
          ~/.cargo/git
          ${{ env.OSXCROSS_TARGET }}
          ${{ env.OSXCROSS_FOLDER }}/target/bin

    - shell: bash
      if: steps.cache.outputs.cache-hit != 'true'
      env:
        SDK_VERSION: "${{ inputs.osx-version }}"
        UNATTENDED: "yes"
      run: |
        cd "$GITHUB_ACTION_PATH/osxcross"
        bash ./build.sh

    - shell: bash
      run: |
        echo "::group::Setting up Bin files"
        OSXCROSS_FOLDER="$(echo "$GITHUB_ACTION_PATH/osxcross" | sed 's/\.\/*//g')"
        echo "OSXCROSS Folder = ${OSXCROSS_FOLDER}"

        if [ ! -d "$OSXCROSS_FOLDER/target/bin" ]; then
          echo "Error! Failed to find ${OSXCROSS_FOLDER}/target/bin folder!"
          exit 1
        else
          if hash sudo 2>/dev/null; then
            sudo chmod +x $OSXCROSS_FOLDER/target/bin/*
          else
            chmod +x $OSXCROSS_FOLDER/target/bin/*
          fi
        fi

        echo "::endgroup::"

        echo "::group::Finding Executables"
        echo "$OSXCROSS_FOLDER/target/bin" >> $GITHUB_PATH
        findTarget() {
          local file="$(find "$OSXCROSS_FOLDER/target/bin" -name "$1")"
          echo "$(basename $file)"
        }

        LINKER_FILE_X86_64="$(findTarget "x86_64-apple-darwin*-clang")"
        AR_FILE_X86_64="$(findTarget "x86_64-apple-darwin*-ar")"
        LINKER_FILE_AARCH64="$(findTarget "aarch64-apple-darwin*-clang")"
        AR_FILE_AARCH64="$(findTarget "aarch64-apple-darwin*-ar")"
        echo "::endgroup::"

        echo "Setting: CARGO_TARGET_X86_64_APPLE_DARWIN_RUSTFLAGS=\"-C linker=${AR_FILE_X86_64} -C linker=${LINKER_FILE_X86_64} -C link-arg=-undefined -C link-arg=dynamic_lookup\""
        echo "CARGO_TARGET_X86_64_APPLE_DARWIN_LINKER=${LINKER_FILE_X86_64}" >> $GITHUB_ENV
        echo "CARGO_TARGET_X86_64_APPLE_DARWIN_RUSTFLAGS=-Car=${AR_FILE_X86_64},-Clink-arg=-undefined,-Clink-arg=dynamic_lookup" >> $GITHUB_ENV

        echo "Setting: CARGO_TARGET_AARCH64_APPLE_DARWIN_RUSTFLAGS=\"-C linker=${AR_FILE_AARCH64} -C linker=${LINKER_FILE_AARCH64} -C link-arg=-undefined -C link-arg=dynamic_lookup\""
        echo "CARGO_TARGET_AARCH64_APPLE_DARWIN_LINKER=${LINKER_FILE_AARCH64}" >> $GITHUB_ENV
        echo "CARGO_TARGET_AARCH64_APPLE_DARWIN_RUSTFLAGS=-Car=${AR_FILE_AARCH64},-Clink-arg=-undefined,-Clink-arg=dynamic_lookup" >> $GITHUB_ENV
